version: '3.3'

services:
    web:
        build: .
        container_name: lightbot-frontend
        environment:
            - VIRTUAL_HOST=bot.bondarenkoid.dev
            - VIRTUAL_PORT=80
        volumes:
            - ./docker/certs:/etc/nginx/certs
        restart: always
        networks:
            - frontend

networks:
    frontend:
        external: true
