version: '3.3'

services:
    app-front:
        build: .
        container_name: lightbot-front
        volumes:
            - ./docker/certs:/etc/nginx/certs
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - lightbot

networks:
    lightbot:
        external: true
