version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - docker/nginx/certs:/etc/nginx/certs:ro

networks:
  default:
    external:
      name: app-network
