version: '3.8'

services:
    lightbot-frontend:
        build: .
        container_name: lightbot-frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/certs:/etc/nginx/certs
        restart: always
