version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs:ro

networks:
  default:
    external:
      name: app-network
