version: '3.3'

services:
    web:
        build: .
        container_name: lightbot-frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/certs:/etc/nginx/certs
        restart: always
