version: '3.3'

services:
    web:
        build: .
        container_name: lightbot-frontend
        volumes:
            - ./docker/certs:/etc/nginx/certs
        restart: always
        networks:
            - frontend

networks:
    frontend:
        external: true
